server:
  port: 8081
spring:  cloud:    config:      server:        git:          default-label: main
          uri: https://github.com/luisparracamara/microservices-tutorial
          search-paths:          - config-data
  
  application:    name: config-service