server:
  port: 8081
spring:  cloud:    config:      server:        git:
          username: luisparracamara
          password: cocoritsonora14          default-label: gateway
          uri: https://github.com/luisparracamara/microservices-tutorial
          search-paths:          - config-data
  
  application:    name: config-service